services:
  template-node-hapi-backend:
    build:
      context: .
      target: development
    volumes:
      - ./src:/home/node/src
      - ./package.json:/home/node/package.json
      - ./vitest.config.js:/home/node/vitest.config.js
